DROP INDEX PrimaryKey ON RegExp;

ALTER TABLE RegExp ALTER COLUMN [RegExp] TEXT;
ALTER TABLE RegExp ADD COLUMN [ID] AUTOINCREMENT PRIMARY KEY;
ALTER TABLE RegExp ADD COLUMN [GUID] TEXT(40);
ALTER TABLE RegExp ADD COLUMN [Description] MEMO;

ALTER TABLE ColRegExp ADD COLUMN [GUID] TEXT(40);
ALTER TABLE ColRegExp ADD COLUMN [Description] MEMO;
